### ISSUE TITLE
index.mjs is missing?

### ISSUE THREAD

**Issue by jleppert** [maierfelix/nvk-examples#1]
$ npm run start --vkversion=1.1.101

> nvk-examples@0.0.1 start /home/johnathan/nvk-examples
> node --inspect --experimental-modules ./index.mjs

Debugger listening on ws://127.0.0.1:9229/2eb99809-407d-4fdf-881c-b967ae190f36
For help, see: https://nodejs.org/en/docs/inspector
(node:10869) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/cjs/loader.js:798
      internalBinding('util').triggerFatalException(e);
                              ^

Error: Cannot find module /home/johnathan/nvk-examples/index.mjs
    at search (internal/modules/esm/default_resolve.js:29:12)
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:65:11)
    at Loader.resolve (internal/modules/esm/loader.js:58:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:113:40)
    at Loader.import (internal/modules/esm/loader.js:99:28)
    at asyncESM.loaderPromise.then (internal/modules/cjs/loader.js:795:27)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nvk-examples@0.0.1 start: `node --inspect --experimental-modules ./index.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nvk-examples@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/johnathan/.npm/_logs/2019-03-05T11_29_36_664Z-debug.log

**Comment by maierfelix** [comment]
As the README states, you have to navigate into an example and run `npm run start..` from there, not from the root folder

**Comment by jleppert** [comment]
Yeah whoops sorry eventually figured it out ;)
